const dayTemplate = {
  0: "initial",
  1: "initial",
  2: "initial",
  3: "initial",
  4: "initial",
  5: "initial",
  6: "initial",
  7: "initial",
  8: "initial",
  9: "initial",
  10: "initial",
  11: "initial",
  12: "initial",
  14: "initial",
  15: "initial",
  16: "initial",
  17: "initial",
  18: "initial",
  19: "initial",
  20: "initial",
  21: "initial",
  22: "initial",
  23: "initial",
  24: "initial",
  25: "initial",
  26: "initial",
  27: "initial",
  28: "initial",
  29: "initial",
  30: "initial",
  31: "initial",
  32: "initial",
  33: "initial",
  34: "initial",
  35: "initial",
  36: "initial",
  37: "initial",
  38: "initial",
  39: "initial",
  40: "initial",
};

export const dataTemplate = (week: number) => {
  return {
    week,
    monday: dayTemplate,
    tuesday: dayTemplate,
    wednesday: dayTemplate,
    thursday: dayTemplate,
    friday: dayTemplate,
    saturday: dayTemplate,
    sunday: dayTemplate,
  };
};
